=== ca-mantis-shrimp/Todoist.nvim/schemas/todoist_sync_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Example API Response",
  "type": "object",
  "properties": {
    "projects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "is_archived": { "type": "boolean" },
          "color": { "type": "string" },
          "shared": { "type": "boolean" },
          "inbox_project": { "type": "boolean" },
          "id": { "type": "string" },
          "collapsed": { "type": "boolean" },
          "child_order": { "type": "integer" },
          "name": { "type": "string" },
          "is_deleted": { "type": "boolean" },
          "parent_id": { 
            "type": ["string", "null"]
          },
          "view_style": { "type": "string" }
        },
        "required": ["is_archived", "color", "shared", "inbox_project", "id", "collapsed", "child_order", "name", "is_deleted", "view_style"],
        "additionalProperties": true
      }
    },
    "full_sync": { "type": "boolean" },
    "temp_id_mapping": {
      "type": "object",
      "additionalProperties": true
    },
    "sync_token": { "type": "string" }
  },
  "required": ["full_sync", "temp_id_mapping", "sync_token"],
  "additionalProperties": true
}

=== ca-mantis-shrimp/Todoist.nvim/tests/schema/example_todoist_sync_response.json
{
  "projects": [
    {
      "is_archived": false,
      "color": "lime_green",
      "shared": false,
      "inbox_project": true,
      "id": "220474322",
      "collapsed": false,
      "child_order": 0,
      "name": "Inbox",
      "is_deleted": false,
      "parent_id": null,
      "view_style": "list"
    }
  ],
  "full_sync": true,
  "temp_id_mapping": {},
  "sync_token": "kMiTgSIk6QGD83xqMJ9ILknYyEsOoLXyFCnnXvkb4mb0oCK0-IwpKfdGvrcf"
}
